### ISSUE TITLE
Deprecated function calls

### ISSUE THREAD

**Issue by rasmusbe** [deler-aziz/fuel_prices_sweden#61]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

```Detected that custom integration 'fuel_prices_sweden' calls async_forward_entry_setup for integration, fuel_prices_sweden with title: Fuel Prices and entry_id: 01J6YVWFPC5FWR4VJDMA0RJYPA, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/fuel_prices_sweden/__init__.py, line 47: hass.async_create_task(, please create a bug report at https://github.com/deler-aziz/fuel_prices_sweden/issues```

### Reproduction steps

1. 
2.
3.
...

### Debug logs

```text
.
```

**Comment by deler-aziz** [comment]
Thank you for raising the issue. It will be fixed soon.
