### ISSUE TITLE
show kr/l

### ISSUE THREAD

**Issue by razzietheman** [deler-aziz/fuel_prices_sweden#65]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

please fix the sensor to showing kr/l even in history and not only like now it shows only 16,88

### Describe the solution you'd like

I want it to show like 16,88 kr/l even in history tab

### Describe alternatives you've considered

.

### Additional context

.

**Comment by deler-aziz** [comment]
Thank you for creating the issue, I will try to implement the unit as soon as possible

**Comment by deler-aziz** [comment]
The issue has been fixed in [1.2.0](https://github.com/deler-aziz/fuel_prices_sweden/releases/tag/1.2.0)
