### ISSUE TITLE
Add station to the mix.

### ISSUE THREAD

**Issue by PetrolHead2** [deler-aziz/fuel_prices_sweden#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Different station have different prices.

### Describe the solution you'd like

Instead of checking the official web sites for prices, why not use https://bensinpriser.nu/

### Describe alternatives you've considered

Also check out this site
https://www.henrikhjelm.se/api/index2.php
He are using bensinpriser.nu for prices.

### Additional context

Since the price is different for different station this would be more accurate.

**Comment by deler-aziz** [comment]
Thank you for creating this issue. To my knowledge, https://bensinpriser.nu/ relies on user-submitted updates for prices, which may result in inaccuracies. Please correct me if I am mistaken.

**Comment by PetrolHead2** [comment]
> Thank you for creating this issue. To my knowledge, https://bensinpriser.nu/ relies on user-submitted updates for prices, which may result in inaccuracies. Please correct me if I am mistaken.

Well, they don't disclose their sources but they update with new prices almost momentarily so I guess the don't only relying on the crowd.
For ST1 you can find more detailed prices here:
https://www.st1.se/billig-bensin

**Comment by deler-aziz** [comment]
> Well, they don't disclose their sources but they update with new prices almost momentarily so I guess the don't only relying on the crowd. For ST1 you can find more detailed prices here: https://www.st1.se/billig-bensin

This is a quote from their website. 

> Bensinpriser.nu kan inte garantera att uppgifterna på denna sida stämmer. Vi har övervakning av alla uppdateringar av priser och försöker på så sätt få bort felaktiga priser.......

**Comment by deler-aziz** [comment]
I am closing this issue as there are currently no plans to use https://bensinpriser.nu/.
