### ISSUE TITLE
The README.md layout for supported fuels

### ISSUE THREAD

**Issue by h00g** [deler-aziz/fuel_prices_sweden#84]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Tables are normally used to show structured data, e.g
- rows for items, cities, persons 
- columns for distinct properties of three entities 

https://github.com/deler-aziz/fuel_prices_sweden?tab=readme-ov-file#%EF%B8%8E-supported-stations-and-fuel-types has tables but they do not seem to be typed as above but rather as a  visual container.

I suggest that you use bullet lists instead, or have one row per fuel type and use columns to denote type of fuel, octane and/or other important aspects.

That change would make it easier to see which kind of diesel, petrol or ethanol that are available.

### Reproduction steps

N/A

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by deler-aziz** [comment]
Thank you for creating this issue.

However, as far as I know, there are no specific rules or definitions on how markdown files should be formatted.
Additionally, I don’t see much value in making this change, as the supported fuels are already clearly listed, even using the table format.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/776714e1-62dc-4e89-8fbd-4cfa14374996">
