### ISSUE TITLE
ST1 Prices not showing

### ISSUE THREAD

**Issue by DJKatastrof** [deler-aziz/fuel_prices_sweden#92]
### System Health details

ST1 Prices not showing

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

ST1 Prices not showing

### Reproduction steps

Tried removing and adding ST1. Removed integration and added

### Debug logs

```text
No logs.
```

**Comment by Birdman86** [comment]
Same issue...

**Comment by deler-aziz** [comment]
It seems that ST1 and Shell have changed the way their websites operate. It appears they are now using some kind of CMS to dynamically create pages.

I will work on resolving this issue as soon as possible.

**Comment by deler-aziz** [comment]
The issue has been fixed in 1.5.0 please update your integration to lates version. Please let me know if you have found anyother issues.

Thank you!
