### ISSUE TITLE
Tanka

### ISSUE THREAD

**Issue by kempe1993** [deler-aziz/fuel_prices_sweden#97]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/deler-aziz/fuel_prices_sweden/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No 98 for tank

### Describe the solution you'd like

Add 98

### Describe alternatives you've considered

Non

### Additional context

No

**Comment by deler-aziz** [comment]
Unfortunately currently Tanka is not publishing any price for 98.

![image](https://github.com/user-attachments/assets/db33cf79-8ba2-4936-a07f-c344037d65ee)

I wll close this issue, feel free to open a new one when Tanka has add support for 98
